### ISSUE TITLE
solana program deploy error

### ISSUE THREAD

**Issue by Kelvin-1013** [Kelvin-1013/presale-project#130]
I reduce solana program and try to deploy
everytime this error : Error: Deploying program failed: RPC response error -32002: Transaction simulation failed: Error processing Instruction 0: account data too small for instruction [3 log messages]
There was a problem deploying: Output { status: ExitStatus(unix_wait_status(256)), stdout: "", stderr: "" }.
origin .so size : 330.3k
new .so size : 331.824k

![image](https://github.com/user-attachments/assets/59174689-aa7d-4953-825f-0f2fcaabec18)

**Comment by sventha-fan** [comment]
I solve this problem
The reason is because difference between size of progrm.
close program and rebuild and redeploy then it solve,
you will not lose your money
